---
# tasks file for ./roles/nginx

- name: configure / Start firewalld
  systemd:
    name: "firewalld"
    state: restarted
    enabled: yes

- name: check_install / Allow ports for firewalld
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items: "{{ nginx_firewalld_port }}"
